# Generated by Django 5.1.6 on 2025-02-26 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='artist',
        ),
    ]
