# Generated by Django 5.1.6 on 2025-02-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_captchaverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coach_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
