# Generated by Django 5.1.6 on 2025-02-26 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_trainingsession_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='api.artist'),
        ),
    ]
