# Generated by Django 5.1.6 on 2025-02-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_user_coach_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("artist", "Artist"),
                    ("coach", "Coach"),
                    ("director", "Director"),
                ],
                default="artist",
                max_length=10,
            ),
        ),
    ]
