# Generated by Django 5.1.6 on 2025-02-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trainingsession_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='total_activities_joined',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
