# Generated by Django 5.1.6 on 2025-02-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_artist_total_activities_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubactivity',
            name='participants_joined',
            field=models.IntegerField(default=0),
        ),
    ]
