# Generated by Django 5.1.6 on 2025-02-22 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_artist_clubactivity_coach_injury_trainingattendance_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clubactivity",
            old_name="participants",
            new_name="registered_participants",
        ),
        migrations.AddField(
            model_name="artist",
            name="total_performance_hours",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="artist",
            name="total_sessions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="artist",
            name="total_training_hours",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="location",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="artist",
            name="attendance_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "managed_artists",
                    models.ManyToManyField(
                        blank=True, related_name="directors_managed", to="api.artist"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="director_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
