# Generated by Django 5.1.6 on 2025-02-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clubactivity_participants_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='artist',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='artist',
            field=models.ManyToManyField(related_name='training_sessions', to='api.artist'),
        ),
    ]
