# Generated by Django 5.1.6 on 2025-02-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_trainingsession_artist_trainingsession_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='artist',
            new_name='artists',
        ),
    ]
