# Generated by Django 5.1.6 on 2025-02-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0006_rename_participants_clubactivity_registered_participants_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_picture/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="guardian_name",
            field=models.CharField(
                blank=True, default="N/A", max_length=255, null=True
            ),
        ),
    ]
