# Generated by Django 5.1.6 on 2025-02-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_user_profile_picture_alter_user_guardian_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
