# Generated by Django 5.1.6 on 2025-02-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='location',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='name',
        ),
        migrations.AddField(
            model_name='clubactivity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='artist_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='coach_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='performance_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='session_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='skills_improved',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('coach', 'Coach'), ('director', 'Director')], default='artist', max_length=50),
        ),
    ]
