# Generated by Django 5.1.6 on 2025-02-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='date',
            field=models.DateField(),
        ),
    ]
